[package]
name = "rchan"
version = "1.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
reqwest = { version = "0.12", features = ["blocking"] }
regex = "1"
anyhow = "1"
colored = "2"
